twitter:
  keys:
    api_key: 'Q4VtL84hd8FQOJclZm8wJAJMY'
    api_secrect: 'IPvC2mpkCrt0aRokxc6OLgj02mQWqT0awDDYeeCXqDxYftIwHb'
    token: '391062851-kTULGsnSWnUAEEuN0pKeZNWCl0v0CVMMIG5gsDit'
    token_secrect: '3zycOQKalhVS6d78AT1V2vkviMtVRvDWjX2yGi9rH9Kau'
database:
  host: 'localhost'
  port: '3306'
  user: 'root'
  pass: 'Zzehel.1112'
  db: 'Twitter'